#
# This is a generated file.
#

api.version=v1.0
batch.engine.entity.class.name=fin.services.rest.dto.v1_0.CreditApplication
batch.engine.task.item.delegate=true
batch.planner.export.enabled=true
batch.planner.import.enabled=true
entity.class.name=fin.services.rest.dto.v1_0.CreditApplication
osgi.jaxrs.application.select=(osgi.jaxrs.name=FinServicesRest)
osgi.jaxrs.resource=true