#
# This is a generated file.
#

api.version=v1.0
openapi.resource=true
openapi.resource.path=/fin-services-rest
osgi.jaxrs.application.select=(osgi.jaxrs.name=FinServicesRest)
osgi.jaxrs.resource=true