/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package fin.services.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import fin.services.model.FinAccount;
import fin.services.model.FinAccountModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FinAccount service. Represents a row in the &quot;FinServices_FinAccount&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FinAccountModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FinAccountImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FinAccountImpl
 * @generated
 */
public class FinAccountModelImpl
	extends BaseModelImpl<FinAccount> implements FinAccountModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fin account model instance should use the <code>FinAccount</code> interface instead.
	 */
	public static final String TABLE_NAME = "FinServices_FinAccount";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"accountId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"ownerUserId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"accountNumber", Types.VARCHAR},
		{"accountName", Types.VARCHAR}, {"accountType", Types.VARCHAR},
		{"balance", Types.DOUBLE}, {"status", Types.INTEGER},
		{"cardScheme", Types.VARCHAR}, {"cardBrand", Types.VARCHAR},
		{"cardBankName", Types.VARCHAR}, {"cardCountryName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("accountId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ownerUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("accountNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("accountName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("accountType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("balance", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("cardScheme", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("cardBrand", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("cardBankName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("cardCountryName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FinServices_FinAccount (uuid_ VARCHAR(75) null,accountId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,ownerUserId LONG,createDate DATE null,modifiedDate DATE null,accountNumber VARCHAR(75) null,accountName VARCHAR(75) null,accountType VARCHAR(75) null,balance DOUBLE,status INTEGER,cardScheme VARCHAR(75) null,cardBrand VARCHAR(75) null,cardBankName VARCHAR(75) null,cardCountryName VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table FinServices_FinAccount";

	public static final String ORDER_BY_JPQL = " ORDER BY ";

	public static final String ORDER_BY_SQL = " ORDER BY ";

	public static final String ORDER_BY_SQL_INLINE_DISTINCT = " ORDER BY ";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ACCOUNTNUMBER_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long OWNERUSERID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FinAccountModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _accountId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAccountId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _accountId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FinAccount.class;
	}

	@Override
	public String getModelClassName() {
		return FinAccount.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FinAccount, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FinAccount, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FinAccount, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((FinAccount)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FinAccount, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FinAccount, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FinAccount)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FinAccount, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FinAccount, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<FinAccount, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<FinAccount, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<FinAccount, Object>>();

			attributeGetterFunctions.put("uuid", FinAccount::getUuid);
			attributeGetterFunctions.put("accountId", FinAccount::getAccountId);
			attributeGetterFunctions.put("groupId", FinAccount::getGroupId);
			attributeGetterFunctions.put("companyId", FinAccount::getCompanyId);
			attributeGetterFunctions.put("userId", FinAccount::getUserId);
			attributeGetterFunctions.put("userName", FinAccount::getUserName);
			attributeGetterFunctions.put(
				"ownerUserId", FinAccount::getOwnerUserId);
			attributeGetterFunctions.put(
				"createDate", FinAccount::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", FinAccount::getModifiedDate);
			attributeGetterFunctions.put(
				"accountNumber", FinAccount::getAccountNumber);
			attributeGetterFunctions.put(
				"accountName", FinAccount::getAccountName);
			attributeGetterFunctions.put(
				"accountType", FinAccount::getAccountType);
			attributeGetterFunctions.put("balance", FinAccount::getBalance);
			attributeGetterFunctions.put("status", FinAccount::getStatus);
			attributeGetterFunctions.put(
				"cardScheme", FinAccount::getCardScheme);
			attributeGetterFunctions.put("cardBrand", FinAccount::getCardBrand);
			attributeGetterFunctions.put(
				"cardBankName", FinAccount::getCardBankName);
			attributeGetterFunctions.put(
				"cardCountryName", FinAccount::getCardCountryName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<FinAccount, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<FinAccount, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<FinAccount, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<FinAccount, String>)FinAccount::setUuid);
			attributeSetterBiConsumers.put(
				"accountId",
				(BiConsumer<FinAccount, Long>)FinAccount::setAccountId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<FinAccount, Long>)FinAccount::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<FinAccount, Long>)FinAccount::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<FinAccount, Long>)FinAccount::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<FinAccount, String>)FinAccount::setUserName);
			attributeSetterBiConsumers.put(
				"ownerUserId",
				(BiConsumer<FinAccount, Long>)FinAccount::setOwnerUserId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<FinAccount, Date>)FinAccount::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<FinAccount, Date>)FinAccount::setModifiedDate);
			attributeSetterBiConsumers.put(
				"accountNumber",
				(BiConsumer<FinAccount, String>)FinAccount::setAccountNumber);
			attributeSetterBiConsumers.put(
				"accountName",
				(BiConsumer<FinAccount, String>)FinAccount::setAccountName);
			attributeSetterBiConsumers.put(
				"accountType",
				(BiConsumer<FinAccount, String>)FinAccount::setAccountType);
			attributeSetterBiConsumers.put(
				"balance",
				(BiConsumer<FinAccount, Double>)FinAccount::setBalance);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<FinAccount, Integer>)FinAccount::setStatus);
			attributeSetterBiConsumers.put(
				"cardScheme",
				(BiConsumer<FinAccount, String>)FinAccount::setCardScheme);
			attributeSetterBiConsumers.put(
				"cardBrand",
				(BiConsumer<FinAccount, String>)FinAccount::setCardBrand);
			attributeSetterBiConsumers.put(
				"cardBankName",
				(BiConsumer<FinAccount, String>)FinAccount::setCardBankName);
			attributeSetterBiConsumers.put(
				"cardCountryName",
				(BiConsumer<FinAccount, String>)FinAccount::setCardCountryName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getAccountId() {
		return _accountId;
	}

	@Override
	public void setAccountId(long accountId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_accountId = accountId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public long getOwnerUserId() {
		return _ownerUserId;
	}

	@Override
	public void setOwnerUserId(long ownerUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ownerUserId = ownerUserId;
	}

	@Override
	public String getOwnerUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getOwnerUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setOwnerUserUuid(String ownerUserUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalOwnerUserId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("ownerUserId"));
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getAccountNumber() {
		if (_accountNumber == null) {
			return "";
		}
		else {
			return _accountNumber;
		}
	}

	@Override
	public void setAccountNumber(String accountNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_accountNumber = accountNumber;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalAccountNumber() {
		return getColumnOriginalValue("accountNumber");
	}

	@Override
	public String getAccountName() {
		if (_accountName == null) {
			return "";
		}
		else {
			return _accountName;
		}
	}

	@Override
	public void setAccountName(String accountName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_accountName = accountName;
	}

	@Override
	public String getAccountType() {
		if (_accountType == null) {
			return "";
		}
		else {
			return _accountType;
		}
	}

	@Override
	public void setAccountType(String accountType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_accountType = accountType;
	}

	@Override
	public double getBalance() {
		return _balance;
	}

	@Override
	public void setBalance(double balance) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_balance = balance;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public String getCardScheme() {
		if (_cardScheme == null) {
			return "";
		}
		else {
			return _cardScheme;
		}
	}

	@Override
	public void setCardScheme(String cardScheme) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cardScheme = cardScheme;
	}

	@Override
	public String getCardBrand() {
		if (_cardBrand == null) {
			return "";
		}
		else {
			return _cardBrand;
		}
	}

	@Override
	public void setCardBrand(String cardBrand) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cardBrand = cardBrand;
	}

	@Override
	public String getCardBankName() {
		if (_cardBankName == null) {
			return "";
		}
		else {
			return _cardBankName;
		}
	}

	@Override
	public void setCardBankName(String cardBankName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cardBankName = cardBankName;
	}

	@Override
	public String getCardCountryName() {
		if (_cardCountryName == null) {
			return "";
		}
		else {
			return _cardCountryName;
		}
	}

	@Override
	public void setCardCountryName(String cardCountryName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cardCountryName = cardCountryName;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(FinAccount.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FinAccount.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FinAccount toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FinAccount>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FinAccountImpl finAccountImpl = new FinAccountImpl();

		finAccountImpl.setUuid(getUuid());
		finAccountImpl.setAccountId(getAccountId());
		finAccountImpl.setGroupId(getGroupId());
		finAccountImpl.setCompanyId(getCompanyId());
		finAccountImpl.setUserId(getUserId());
		finAccountImpl.setUserName(getUserName());
		finAccountImpl.setOwnerUserId(getOwnerUserId());
		finAccountImpl.setCreateDate(getCreateDate());
		finAccountImpl.setModifiedDate(getModifiedDate());
		finAccountImpl.setAccountNumber(getAccountNumber());
		finAccountImpl.setAccountName(getAccountName());
		finAccountImpl.setAccountType(getAccountType());
		finAccountImpl.setBalance(getBalance());
		finAccountImpl.setStatus(getStatus());
		finAccountImpl.setCardScheme(getCardScheme());
		finAccountImpl.setCardBrand(getCardBrand());
		finAccountImpl.setCardBankName(getCardBankName());
		finAccountImpl.setCardCountryName(getCardCountryName());

		finAccountImpl.resetOriginalValues();

		return finAccountImpl;
	}

	@Override
	public FinAccount cloneWithOriginalValues() {
		FinAccountImpl finAccountImpl = new FinAccountImpl();

		finAccountImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		finAccountImpl.setAccountId(
			this.<Long>getColumnOriginalValue("accountId"));
		finAccountImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		finAccountImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		finAccountImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		finAccountImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		finAccountImpl.setOwnerUserId(
			this.<Long>getColumnOriginalValue("ownerUserId"));
		finAccountImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		finAccountImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		finAccountImpl.setAccountNumber(
			this.<String>getColumnOriginalValue("accountNumber"));
		finAccountImpl.setAccountName(
			this.<String>getColumnOriginalValue("accountName"));
		finAccountImpl.setAccountType(
			this.<String>getColumnOriginalValue("accountType"));
		finAccountImpl.setBalance(
			this.<Double>getColumnOriginalValue("balance"));
		finAccountImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		finAccountImpl.setCardScheme(
			this.<String>getColumnOriginalValue("cardScheme"));
		finAccountImpl.setCardBrand(
			this.<String>getColumnOriginalValue("cardBrand"));
		finAccountImpl.setCardBankName(
			this.<String>getColumnOriginalValue("cardBankName"));
		finAccountImpl.setCardCountryName(
			this.<String>getColumnOriginalValue("cardCountryName"));

		return finAccountImpl;
	}

	@Override
	public int compareTo(FinAccount finAccount) {
		int value = 0;

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FinAccount)) {
			return false;
		}

		FinAccount finAccount = (FinAccount)object;

		long primaryKey = finAccount.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FinAccount> toCacheModel() {
		FinAccountCacheModel finAccountCacheModel = new FinAccountCacheModel();

		finAccountCacheModel.uuid = getUuid();

		String uuid = finAccountCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			finAccountCacheModel.uuid = null;
		}

		finAccountCacheModel.accountId = getAccountId();

		finAccountCacheModel.groupId = getGroupId();

		finAccountCacheModel.companyId = getCompanyId();

		finAccountCacheModel.userId = getUserId();

		finAccountCacheModel.userName = getUserName();

		String userName = finAccountCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			finAccountCacheModel.userName = null;
		}

		finAccountCacheModel.ownerUserId = getOwnerUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			finAccountCacheModel.createDate = createDate.getTime();
		}
		else {
			finAccountCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			finAccountCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			finAccountCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		finAccountCacheModel.accountNumber = getAccountNumber();

		String accountNumber = finAccountCacheModel.accountNumber;

		if ((accountNumber != null) && (accountNumber.length() == 0)) {
			finAccountCacheModel.accountNumber = null;
		}

		finAccountCacheModel.accountName = getAccountName();

		String accountName = finAccountCacheModel.accountName;

		if ((accountName != null) && (accountName.length() == 0)) {
			finAccountCacheModel.accountName = null;
		}

		finAccountCacheModel.accountType = getAccountType();

		String accountType = finAccountCacheModel.accountType;

		if ((accountType != null) && (accountType.length() == 0)) {
			finAccountCacheModel.accountType = null;
		}

		finAccountCacheModel.balance = getBalance();

		finAccountCacheModel.status = getStatus();

		finAccountCacheModel.cardScheme = getCardScheme();

		String cardScheme = finAccountCacheModel.cardScheme;

		if ((cardScheme != null) && (cardScheme.length() == 0)) {
			finAccountCacheModel.cardScheme = null;
		}

		finAccountCacheModel.cardBrand = getCardBrand();

		String cardBrand = finAccountCacheModel.cardBrand;

		if ((cardBrand != null) && (cardBrand.length() == 0)) {
			finAccountCacheModel.cardBrand = null;
		}

		finAccountCacheModel.cardBankName = getCardBankName();

		String cardBankName = finAccountCacheModel.cardBankName;

		if ((cardBankName != null) && (cardBankName.length() == 0)) {
			finAccountCacheModel.cardBankName = null;
		}

		finAccountCacheModel.cardCountryName = getCardCountryName();

		String cardCountryName = finAccountCacheModel.cardCountryName;

		if ((cardCountryName != null) && (cardCountryName.length() == 0)) {
			finAccountCacheModel.cardCountryName = null;
		}

		return finAccountCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FinAccount, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FinAccount, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FinAccount, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((FinAccount)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FinAccount>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					FinAccount.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _accountId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private long _ownerUserId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _accountNumber;
	private String _accountName;
	private String _accountType;
	private double _balance;
	private int _status;
	private String _cardScheme;
	private String _cardBrand;
	private String _cardBankName;
	private String _cardCountryName;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<FinAccount, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FinAccount)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("accountId", _accountId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("ownerUserId", _ownerUserId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("accountNumber", _accountNumber);
		_columnOriginalValues.put("accountName", _accountName);
		_columnOriginalValues.put("accountType", _accountType);
		_columnOriginalValues.put("balance", _balance);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("cardScheme", _cardScheme);
		_columnOriginalValues.put("cardBrand", _cardBrand);
		_columnOriginalValues.put("cardBankName", _cardBankName);
		_columnOriginalValues.put("cardCountryName", _cardCountryName);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("accountId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("ownerUserId", 64L);

		columnBitmasks.put("createDate", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		columnBitmasks.put("accountNumber", 512L);

		columnBitmasks.put("accountName", 1024L);

		columnBitmasks.put("accountType", 2048L);

		columnBitmasks.put("balance", 4096L);

		columnBitmasks.put("status", 8192L);

		columnBitmasks.put("cardScheme", 16384L);

		columnBitmasks.put("cardBrand", 32768L);

		columnBitmasks.put("cardBankName", 65536L);

		columnBitmasks.put("cardCountryName", 131072L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FinAccount _escapedModel;

}