/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package fin.services.model.impl;

import fin.services.model.FinAccount;
import fin.services.service.FinAccountLocalServiceUtil;

/**
 * The extended model base implementation for the FinAccount service. Represents a row in the &quot;FinServices_FinAccount&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FinAccountImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FinAccountImpl
 * @see FinAccount
 * @generated
 */
public abstract class FinAccountBaseImpl
	extends FinAccountModelImpl implements FinAccount {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fin account model instance should use the <code>FinAccount</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			FinAccountLocalServiceUtil.addFinAccount(this);
		}
		else {
			FinAccountLocalServiceUtil.updateFinAccount(this);
		}
	}

}