/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package fin.services.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import fin.services.model.FinCreditApp;
import fin.services.model.FinCreditAppModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FinCreditApp service. Represents a row in the &quot;FinServices_FinCreditApp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FinCreditAppModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FinCreditAppImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FinCreditAppImpl
 * @generated
 */
public class FinCreditAppModelImpl
	extends BaseModelImpl<FinCreditApp> implements FinCreditAppModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fin credit app model instance should use the <code>FinCreditApp</code> interface instead.
	 */
	public static final String TABLE_NAME = "FinServices_FinCreditApp";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"creditAppId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"accountId", Types.BIGINT}, {"applicantName", Types.VARCHAR},
		{"requestedAmount", Types.DOUBLE}, {"purpose", Types.VARCHAR},
		{"status", Types.INTEGER}, {"reviewNotes", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("creditAppId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("accountId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("applicantName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("requestedAmount", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("purpose", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("reviewNotes", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FinServices_FinCreditApp (uuid_ VARCHAR(75) null,creditAppId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,accountId LONG,applicantName VARCHAR(75) null,requestedAmount DOUBLE,purpose VARCHAR(75) null,status INTEGER,reviewNotes VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table FinServices_FinCreditApp";

	public static final String ORDER_BY_JPQL = " ORDER BY ";

	public static final String ORDER_BY_SQL = " ORDER BY ";

	public static final String ORDER_BY_SQL_INLINE_DISTINCT = " ORDER BY ";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ACCOUNTID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FinCreditAppModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _creditAppId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCreditAppId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _creditAppId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FinCreditApp.class;
	}

	@Override
	public String getModelClassName() {
		return FinCreditApp.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FinCreditApp, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FinCreditApp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FinCreditApp, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FinCreditApp)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FinCreditApp, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FinCreditApp, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FinCreditApp)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FinCreditApp, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FinCreditApp, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<FinCreditApp, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<FinCreditApp, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<FinCreditApp, Object>>();

			attributeGetterFunctions.put("uuid", FinCreditApp::getUuid);
			attributeGetterFunctions.put(
				"creditAppId", FinCreditApp::getCreditAppId);
			attributeGetterFunctions.put("groupId", FinCreditApp::getGroupId);
			attributeGetterFunctions.put(
				"companyId", FinCreditApp::getCompanyId);
			attributeGetterFunctions.put("userId", FinCreditApp::getUserId);
			attributeGetterFunctions.put("userName", FinCreditApp::getUserName);
			attributeGetterFunctions.put(
				"createDate", FinCreditApp::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", FinCreditApp::getModifiedDate);
			attributeGetterFunctions.put(
				"accountId", FinCreditApp::getAccountId);
			attributeGetterFunctions.put(
				"applicantName", FinCreditApp::getApplicantName);
			attributeGetterFunctions.put(
				"requestedAmount", FinCreditApp::getRequestedAmount);
			attributeGetterFunctions.put("purpose", FinCreditApp::getPurpose);
			attributeGetterFunctions.put("status", FinCreditApp::getStatus);
			attributeGetterFunctions.put(
				"reviewNotes", FinCreditApp::getReviewNotes);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<FinCreditApp, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<FinCreditApp, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<FinCreditApp, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<FinCreditApp, String>)FinCreditApp::setUuid);
			attributeSetterBiConsumers.put(
				"creditAppId",
				(BiConsumer<FinCreditApp, Long>)FinCreditApp::setCreditAppId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<FinCreditApp, Long>)FinCreditApp::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<FinCreditApp, Long>)FinCreditApp::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<FinCreditApp, Long>)FinCreditApp::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<FinCreditApp, String>)FinCreditApp::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<FinCreditApp, Date>)FinCreditApp::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<FinCreditApp, Date>)FinCreditApp::setModifiedDate);
			attributeSetterBiConsumers.put(
				"accountId",
				(BiConsumer<FinCreditApp, Long>)FinCreditApp::setAccountId);
			attributeSetterBiConsumers.put(
				"applicantName",
				(BiConsumer<FinCreditApp, String>)
					FinCreditApp::setApplicantName);
			attributeSetterBiConsumers.put(
				"requestedAmount",
				(BiConsumer<FinCreditApp, Double>)
					FinCreditApp::setRequestedAmount);
			attributeSetterBiConsumers.put(
				"purpose",
				(BiConsumer<FinCreditApp, String>)FinCreditApp::setPurpose);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<FinCreditApp, Integer>)FinCreditApp::setStatus);
			attributeSetterBiConsumers.put(
				"reviewNotes",
				(BiConsumer<FinCreditApp, String>)FinCreditApp::setReviewNotes);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getCreditAppId() {
		return _creditAppId;
	}

	@Override
	public void setCreditAppId(long creditAppId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_creditAppId = creditAppId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getAccountId() {
		return _accountId;
	}

	@Override
	public void setAccountId(long accountId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_accountId = accountId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalAccountId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("accountId"));
	}

	@Override
	public String getApplicantName() {
		if (_applicantName == null) {
			return "";
		}
		else {
			return _applicantName;
		}
	}

	@Override
	public void setApplicantName(String applicantName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_applicantName = applicantName;
	}

	@Override
	public double getRequestedAmount() {
		return _requestedAmount;
	}

	@Override
	public void setRequestedAmount(double requestedAmount) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_requestedAmount = requestedAmount;
	}

	@Override
	public String getPurpose() {
		if (_purpose == null) {
			return "";
		}
		else {
			return _purpose;
		}
	}

	@Override
	public void setPurpose(String purpose) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_purpose = purpose;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public String getReviewNotes() {
		if (_reviewNotes == null) {
			return "";
		}
		else {
			return _reviewNotes;
		}
	}

	@Override
	public void setReviewNotes(String reviewNotes) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_reviewNotes = reviewNotes;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(FinCreditApp.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FinCreditApp.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FinCreditApp toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FinCreditApp>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FinCreditAppImpl finCreditAppImpl = new FinCreditAppImpl();

		finCreditAppImpl.setUuid(getUuid());
		finCreditAppImpl.setCreditAppId(getCreditAppId());
		finCreditAppImpl.setGroupId(getGroupId());
		finCreditAppImpl.setCompanyId(getCompanyId());
		finCreditAppImpl.setUserId(getUserId());
		finCreditAppImpl.setUserName(getUserName());
		finCreditAppImpl.setCreateDate(getCreateDate());
		finCreditAppImpl.setModifiedDate(getModifiedDate());
		finCreditAppImpl.setAccountId(getAccountId());
		finCreditAppImpl.setApplicantName(getApplicantName());
		finCreditAppImpl.setRequestedAmount(getRequestedAmount());
		finCreditAppImpl.setPurpose(getPurpose());
		finCreditAppImpl.setStatus(getStatus());
		finCreditAppImpl.setReviewNotes(getReviewNotes());

		finCreditAppImpl.resetOriginalValues();

		return finCreditAppImpl;
	}

	@Override
	public FinCreditApp cloneWithOriginalValues() {
		FinCreditAppImpl finCreditAppImpl = new FinCreditAppImpl();

		finCreditAppImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		finCreditAppImpl.setCreditAppId(
			this.<Long>getColumnOriginalValue("creditAppId"));
		finCreditAppImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		finCreditAppImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		finCreditAppImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		finCreditAppImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		finCreditAppImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		finCreditAppImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		finCreditAppImpl.setAccountId(
			this.<Long>getColumnOriginalValue("accountId"));
		finCreditAppImpl.setApplicantName(
			this.<String>getColumnOriginalValue("applicantName"));
		finCreditAppImpl.setRequestedAmount(
			this.<Double>getColumnOriginalValue("requestedAmount"));
		finCreditAppImpl.setPurpose(
			this.<String>getColumnOriginalValue("purpose"));
		finCreditAppImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		finCreditAppImpl.setReviewNotes(
			this.<String>getColumnOriginalValue("reviewNotes"));

		return finCreditAppImpl;
	}

	@Override
	public int compareTo(FinCreditApp finCreditApp) {
		int value = 0;

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FinCreditApp)) {
			return false;
		}

		FinCreditApp finCreditApp = (FinCreditApp)object;

		long primaryKey = finCreditApp.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FinCreditApp> toCacheModel() {
		FinCreditAppCacheModel finCreditAppCacheModel =
			new FinCreditAppCacheModel();

		finCreditAppCacheModel.uuid = getUuid();

		String uuid = finCreditAppCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			finCreditAppCacheModel.uuid = null;
		}

		finCreditAppCacheModel.creditAppId = getCreditAppId();

		finCreditAppCacheModel.groupId = getGroupId();

		finCreditAppCacheModel.companyId = getCompanyId();

		finCreditAppCacheModel.userId = getUserId();

		finCreditAppCacheModel.userName = getUserName();

		String userName = finCreditAppCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			finCreditAppCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			finCreditAppCacheModel.createDate = createDate.getTime();
		}
		else {
			finCreditAppCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			finCreditAppCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			finCreditAppCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		finCreditAppCacheModel.accountId = getAccountId();

		finCreditAppCacheModel.applicantName = getApplicantName();

		String applicantName = finCreditAppCacheModel.applicantName;

		if ((applicantName != null) && (applicantName.length() == 0)) {
			finCreditAppCacheModel.applicantName = null;
		}

		finCreditAppCacheModel.requestedAmount = getRequestedAmount();

		finCreditAppCacheModel.purpose = getPurpose();

		String purpose = finCreditAppCacheModel.purpose;

		if ((purpose != null) && (purpose.length() == 0)) {
			finCreditAppCacheModel.purpose = null;
		}

		finCreditAppCacheModel.status = getStatus();

		finCreditAppCacheModel.reviewNotes = getReviewNotes();

		String reviewNotes = finCreditAppCacheModel.reviewNotes;

		if ((reviewNotes != null) && (reviewNotes.length() == 0)) {
			finCreditAppCacheModel.reviewNotes = null;
		}

		return finCreditAppCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FinCreditApp, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FinCreditApp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FinCreditApp, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((FinCreditApp)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FinCreditApp>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					FinCreditApp.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _creditAppId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _accountId;
	private String _applicantName;
	private double _requestedAmount;
	private String _purpose;
	private int _status;
	private String _reviewNotes;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<FinCreditApp, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FinCreditApp)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("creditAppId", _creditAppId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("accountId", _accountId);
		_columnOriginalValues.put("applicantName", _applicantName);
		_columnOriginalValues.put("requestedAmount", _requestedAmount);
		_columnOriginalValues.put("purpose", _purpose);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("reviewNotes", _reviewNotes);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("creditAppId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("accountId", 256L);

		columnBitmasks.put("applicantName", 512L);

		columnBitmasks.put("requestedAmount", 1024L);

		columnBitmasks.put("purpose", 2048L);

		columnBitmasks.put("status", 4096L);

		columnBitmasks.put("reviewNotes", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FinCreditApp _escapedModel;

}