/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package fin.services.model.impl;

import fin.services.model.FinCreditApp;
import fin.services.service.FinCreditAppLocalServiceUtil;

/**
 * The extended model base implementation for the FinCreditApp service. Represents a row in the &quot;FinServices_FinCreditApp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FinCreditAppImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FinCreditAppImpl
 * @see FinCreditApp
 * @generated
 */
public abstract class FinCreditAppBaseImpl
	extends FinCreditAppModelImpl implements FinCreditApp {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fin credit app model instance should use the <code>FinCreditApp</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			FinCreditAppLocalServiceUtil.addFinCreditApp(this);
		}
		else {
			FinCreditAppLocalServiceUtil.updateFinCreditApp(this);
		}
	}

}