/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package fin.services.model.impl;

import fin.services.model.FinTransaction;
import fin.services.service.FinTransactionLocalServiceUtil;

/**
 * The extended model base implementation for the FinTransaction service. Represents a row in the &quot;FinServices_FinTransaction&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FinTransactionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FinTransactionImpl
 * @see FinTransaction
 * @generated
 */
public abstract class FinTransactionBaseImpl
	extends FinTransactionModelImpl implements FinTransaction {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fin transaction model instance should use the <code>FinTransaction</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			FinTransactionLocalServiceUtil.addFinTransaction(this);
		}
		else {
			FinTransactionLocalServiceUtil.updateFinTransaction(this);
		}
	}

}