/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package fin.services.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import fin.services.model.FinTransaction;
import fin.services.model.FinTransactionModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FinTransaction service. Represents a row in the &quot;FinServices_FinTransaction&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FinTransactionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FinTransactionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FinTransactionImpl
 * @generated
 */
public class FinTransactionModelImpl
	extends BaseModelImpl<FinTransaction> implements FinTransactionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fin transaction model instance should use the <code>FinTransaction</code> interface instead.
	 */
	public static final String TABLE_NAME = "FinServices_FinTransaction";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"transactionId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"accountId", Types.BIGINT}, {"transactionType", Types.VARCHAR},
		{"amount", Types.DOUBLE}, {"description", Types.VARCHAR},
		{"transactionDate", Types.TIMESTAMP}, {"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("transactionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("accountId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("transactionType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("amount", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("transactionDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FinServices_FinTransaction (uuid_ VARCHAR(75) null,transactionId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,accountId LONG,transactionType VARCHAR(75) null,amount DOUBLE,description VARCHAR(75) null,transactionDate DATE null,status INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table FinServices_FinTransaction";

	public static final String ORDER_BY_JPQL = " ORDER BY ";

	public static final String ORDER_BY_SQL = " ORDER BY ";

	public static final String ORDER_BY_SQL_INLINE_DISTINCT = " ORDER BY ";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ACCOUNTID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FinTransactionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _transactionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTransactionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _transactionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FinTransaction.class;
	}

	@Override
	public String getModelClassName() {
		return FinTransaction.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FinTransaction, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FinTransaction, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FinTransaction, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FinTransaction)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FinTransaction, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FinTransaction, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FinTransaction)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FinTransaction, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FinTransaction, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<FinTransaction, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<FinTransaction, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<FinTransaction, Object>>();

			attributeGetterFunctions.put("uuid", FinTransaction::getUuid);
			attributeGetterFunctions.put(
				"transactionId", FinTransaction::getTransactionId);
			attributeGetterFunctions.put("groupId", FinTransaction::getGroupId);
			attributeGetterFunctions.put(
				"companyId", FinTransaction::getCompanyId);
			attributeGetterFunctions.put("userId", FinTransaction::getUserId);
			attributeGetterFunctions.put(
				"userName", FinTransaction::getUserName);
			attributeGetterFunctions.put(
				"createDate", FinTransaction::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", FinTransaction::getModifiedDate);
			attributeGetterFunctions.put(
				"accountId", FinTransaction::getAccountId);
			attributeGetterFunctions.put(
				"transactionType", FinTransaction::getTransactionType);
			attributeGetterFunctions.put("amount", FinTransaction::getAmount);
			attributeGetterFunctions.put(
				"description", FinTransaction::getDescription);
			attributeGetterFunctions.put(
				"transactionDate", FinTransaction::getTransactionDate);
			attributeGetterFunctions.put("status", FinTransaction::getStatus);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<FinTransaction, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<FinTransaction, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<FinTransaction, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<FinTransaction, String>)FinTransaction::setUuid);
			attributeSetterBiConsumers.put(
				"transactionId",
				(BiConsumer<FinTransaction, Long>)
					FinTransaction::setTransactionId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<FinTransaction, Long>)FinTransaction::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<FinTransaction, Long>)FinTransaction::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<FinTransaction, Long>)FinTransaction::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<FinTransaction, String>)
					FinTransaction::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<FinTransaction, Date>)
					FinTransaction::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<FinTransaction, Date>)
					FinTransaction::setModifiedDate);
			attributeSetterBiConsumers.put(
				"accountId",
				(BiConsumer<FinTransaction, Long>)FinTransaction::setAccountId);
			attributeSetterBiConsumers.put(
				"transactionType",
				(BiConsumer<FinTransaction, String>)
					FinTransaction::setTransactionType);
			attributeSetterBiConsumers.put(
				"amount",
				(BiConsumer<FinTransaction, Double>)FinTransaction::setAmount);
			attributeSetterBiConsumers.put(
				"description",
				(BiConsumer<FinTransaction, String>)
					FinTransaction::setDescription);
			attributeSetterBiConsumers.put(
				"transactionDate",
				(BiConsumer<FinTransaction, Date>)
					FinTransaction::setTransactionDate);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<FinTransaction, Integer>)FinTransaction::setStatus);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getTransactionId() {
		return _transactionId;
	}

	@Override
	public void setTransactionId(long transactionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_transactionId = transactionId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getAccountId() {
		return _accountId;
	}

	@Override
	public void setAccountId(long accountId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_accountId = accountId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalAccountId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("accountId"));
	}

	@Override
	public String getTransactionType() {
		if (_transactionType == null) {
			return "";
		}
		else {
			return _transactionType;
		}
	}

	@Override
	public void setTransactionType(String transactionType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_transactionType = transactionType;
	}

	@Override
	public double getAmount() {
		return _amount;
	}

	@Override
	public void setAmount(double amount) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_amount = amount;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public Date getTransactionDate() {
		return _transactionDate;
	}

	@Override
	public void setTransactionDate(Date transactionDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_transactionDate = transactionDate;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(FinTransaction.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FinTransaction.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FinTransaction toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FinTransaction>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FinTransactionImpl finTransactionImpl = new FinTransactionImpl();

		finTransactionImpl.setUuid(getUuid());
		finTransactionImpl.setTransactionId(getTransactionId());
		finTransactionImpl.setGroupId(getGroupId());
		finTransactionImpl.setCompanyId(getCompanyId());
		finTransactionImpl.setUserId(getUserId());
		finTransactionImpl.setUserName(getUserName());
		finTransactionImpl.setCreateDate(getCreateDate());
		finTransactionImpl.setModifiedDate(getModifiedDate());
		finTransactionImpl.setAccountId(getAccountId());
		finTransactionImpl.setTransactionType(getTransactionType());
		finTransactionImpl.setAmount(getAmount());
		finTransactionImpl.setDescription(getDescription());
		finTransactionImpl.setTransactionDate(getTransactionDate());
		finTransactionImpl.setStatus(getStatus());

		finTransactionImpl.resetOriginalValues();

		return finTransactionImpl;
	}

	@Override
	public FinTransaction cloneWithOriginalValues() {
		FinTransactionImpl finTransactionImpl = new FinTransactionImpl();

		finTransactionImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		finTransactionImpl.setTransactionId(
			this.<Long>getColumnOriginalValue("transactionId"));
		finTransactionImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		finTransactionImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		finTransactionImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		finTransactionImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		finTransactionImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		finTransactionImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		finTransactionImpl.setAccountId(
			this.<Long>getColumnOriginalValue("accountId"));
		finTransactionImpl.setTransactionType(
			this.<String>getColumnOriginalValue("transactionType"));
		finTransactionImpl.setAmount(
			this.<Double>getColumnOriginalValue("amount"));
		finTransactionImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		finTransactionImpl.setTransactionDate(
			this.<Date>getColumnOriginalValue("transactionDate"));
		finTransactionImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));

		return finTransactionImpl;
	}

	@Override
	public int compareTo(FinTransaction finTransaction) {
		int value = 0;

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FinTransaction)) {
			return false;
		}

		FinTransaction finTransaction = (FinTransaction)object;

		long primaryKey = finTransaction.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FinTransaction> toCacheModel() {
		FinTransactionCacheModel finTransactionCacheModel =
			new FinTransactionCacheModel();

		finTransactionCacheModel.uuid = getUuid();

		String uuid = finTransactionCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			finTransactionCacheModel.uuid = null;
		}

		finTransactionCacheModel.transactionId = getTransactionId();

		finTransactionCacheModel.groupId = getGroupId();

		finTransactionCacheModel.companyId = getCompanyId();

		finTransactionCacheModel.userId = getUserId();

		finTransactionCacheModel.userName = getUserName();

		String userName = finTransactionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			finTransactionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			finTransactionCacheModel.createDate = createDate.getTime();
		}
		else {
			finTransactionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			finTransactionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			finTransactionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		finTransactionCacheModel.accountId = getAccountId();

		finTransactionCacheModel.transactionType = getTransactionType();

		String transactionType = finTransactionCacheModel.transactionType;

		if ((transactionType != null) && (transactionType.length() == 0)) {
			finTransactionCacheModel.transactionType = null;
		}

		finTransactionCacheModel.amount = getAmount();

		finTransactionCacheModel.description = getDescription();

		String description = finTransactionCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			finTransactionCacheModel.description = null;
		}

		Date transactionDate = getTransactionDate();

		if (transactionDate != null) {
			finTransactionCacheModel.transactionDate =
				transactionDate.getTime();
		}
		else {
			finTransactionCacheModel.transactionDate = Long.MIN_VALUE;
		}

		finTransactionCacheModel.status = getStatus();

		return finTransactionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FinTransaction, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FinTransaction, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FinTransaction, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((FinTransaction)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FinTransaction>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					FinTransaction.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _transactionId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _accountId;
	private String _transactionType;
	private double _amount;
	private String _description;
	private Date _transactionDate;
	private int _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<FinTransaction, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FinTransaction)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("transactionId", _transactionId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("accountId", _accountId);
		_columnOriginalValues.put("transactionType", _transactionType);
		_columnOriginalValues.put("amount", _amount);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("transactionDate", _transactionDate);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("transactionId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("accountId", 256L);

		columnBitmasks.put("transactionType", 512L);

		columnBitmasks.put("amount", 1024L);

		columnBitmasks.put("description", 2048L);

		columnBitmasks.put("transactionDate", 4096L);

		columnBitmasks.put("status", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FinTransaction _escapedModel;

}