/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package fin.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FinAccount service. Represents a row in the &quot;FinServices_FinAccount&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>fin.services.model.impl.FinAccountModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>fin.services.model.impl.FinAccountImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FinAccount
 * @generated
 */
@ProviderType
public interface FinAccountModel
	extends BaseModel<FinAccount>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fin account model instance should use the {@link FinAccount} interface instead.
	 */

	/**
	 * Returns the primary key of this fin account.
	 *
	 * @return the primary key of this fin account
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fin account.
	 *
	 * @param primaryKey the primary key of this fin account
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this fin account.
	 *
	 * @return the uuid of this fin account
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this fin account.
	 *
	 * @param uuid the uuid of this fin account
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the account ID of this fin account.
	 *
	 * @return the account ID of this fin account
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this fin account.
	 *
	 * @param accountId the account ID of this fin account
	 */
	public void setAccountId(long accountId);

	/**
	 * Returns the group ID of this fin account.
	 *
	 * @return the group ID of this fin account
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this fin account.
	 *
	 * @param groupId the group ID of this fin account
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this fin account.
	 *
	 * @return the company ID of this fin account
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this fin account.
	 *
	 * @param companyId the company ID of this fin account
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this fin account.
	 *
	 * @return the user ID of this fin account
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this fin account.
	 *
	 * @param userId the user ID of this fin account
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this fin account.
	 *
	 * @return the user uuid of this fin account
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this fin account.
	 *
	 * @param userUuid the user uuid of this fin account
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this fin account.
	 *
	 * @return the user name of this fin account
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this fin account.
	 *
	 * @param userName the user name of this fin account
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the owner user ID of this fin account.
	 *
	 * @return the owner user ID of this fin account
	 */
	public long getOwnerUserId();

	/**
	 * Sets the owner user ID of this fin account.
	 *
	 * @param ownerUserId the owner user ID of this fin account
	 */
	public void setOwnerUserId(long ownerUserId);

	/**
	 * Returns the owner user uuid of this fin account.
	 *
	 * @return the owner user uuid of this fin account
	 */
	public String getOwnerUserUuid();

	/**
	 * Sets the owner user uuid of this fin account.
	 *
	 * @param ownerUserUuid the owner user uuid of this fin account
	 */
	public void setOwnerUserUuid(String ownerUserUuid);

	/**
	 * Returns the create date of this fin account.
	 *
	 * @return the create date of this fin account
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this fin account.
	 *
	 * @param createDate the create date of this fin account
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this fin account.
	 *
	 * @return the modified date of this fin account
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this fin account.
	 *
	 * @param modifiedDate the modified date of this fin account
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the account number of this fin account.
	 *
	 * @return the account number of this fin account
	 */
	@AutoEscape
	public String getAccountNumber();

	/**
	 * Sets the account number of this fin account.
	 *
	 * @param accountNumber the account number of this fin account
	 */
	public void setAccountNumber(String accountNumber);

	/**
	 * Returns the account name of this fin account.
	 *
	 * @return the account name of this fin account
	 */
	@AutoEscape
	public String getAccountName();

	/**
	 * Sets the account name of this fin account.
	 *
	 * @param accountName the account name of this fin account
	 */
	public void setAccountName(String accountName);

	/**
	 * Returns the account type of this fin account.
	 *
	 * @return the account type of this fin account
	 */
	@AutoEscape
	public String getAccountType();

	/**
	 * Sets the account type of this fin account.
	 *
	 * @param accountType the account type of this fin account
	 */
	public void setAccountType(String accountType);

	/**
	 * Returns the balance of this fin account.
	 *
	 * @return the balance of this fin account
	 */
	public double getBalance();

	/**
	 * Sets the balance of this fin account.
	 *
	 * @param balance the balance of this fin account
	 */
	public void setBalance(double balance);

	/**
	 * Returns the status of this fin account.
	 *
	 * @return the status of this fin account
	 */
	public int getStatus();

	/**
	 * Sets the status of this fin account.
	 *
	 * @param status the status of this fin account
	 */
	public void setStatus(int status);

	/**
	 * Returns the card scheme of this fin account.
	 *
	 * @return the card scheme of this fin account
	 */
	@AutoEscape
	public String getCardScheme();

	/**
	 * Sets the card scheme of this fin account.
	 *
	 * @param cardScheme the card scheme of this fin account
	 */
	public void setCardScheme(String cardScheme);

	/**
	 * Returns the card brand of this fin account.
	 *
	 * @return the card brand of this fin account
	 */
	@AutoEscape
	public String getCardBrand();

	/**
	 * Sets the card brand of this fin account.
	 *
	 * @param cardBrand the card brand of this fin account
	 */
	public void setCardBrand(String cardBrand);

	/**
	 * Returns the card bank name of this fin account.
	 *
	 * @return the card bank name of this fin account
	 */
	@AutoEscape
	public String getCardBankName();

	/**
	 * Sets the card bank name of this fin account.
	 *
	 * @param cardBankName the card bank name of this fin account
	 */
	public void setCardBankName(String cardBankName);

	/**
	 * Returns the card country name of this fin account.
	 *
	 * @return the card country name of this fin account
	 */
	@AutoEscape
	public String getCardCountryName();

	/**
	 * Sets the card country name of this fin account.
	 *
	 * @param cardCountryName the card country name of this fin account
	 */
	public void setCardCountryName(String cardCountryName);

	@Override
	public FinAccount cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}