/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package fin.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FinCreditApp service. Represents a row in the &quot;FinServices_FinCreditApp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>fin.services.model.impl.FinCreditAppModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>fin.services.model.impl.FinCreditAppImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FinCreditApp
 * @generated
 */
@ProviderType
public interface FinCreditAppModel
	extends BaseModel<FinCreditApp>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fin credit app model instance should use the {@link FinCreditApp} interface instead.
	 */

	/**
	 * Returns the primary key of this fin credit app.
	 *
	 * @return the primary key of this fin credit app
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fin credit app.
	 *
	 * @param primaryKey the primary key of this fin credit app
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this fin credit app.
	 *
	 * @return the uuid of this fin credit app
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this fin credit app.
	 *
	 * @param uuid the uuid of this fin credit app
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the credit app ID of this fin credit app.
	 *
	 * @return the credit app ID of this fin credit app
	 */
	public long getCreditAppId();

	/**
	 * Sets the credit app ID of this fin credit app.
	 *
	 * @param creditAppId the credit app ID of this fin credit app
	 */
	public void setCreditAppId(long creditAppId);

	/**
	 * Returns the group ID of this fin credit app.
	 *
	 * @return the group ID of this fin credit app
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this fin credit app.
	 *
	 * @param groupId the group ID of this fin credit app
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this fin credit app.
	 *
	 * @return the company ID of this fin credit app
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this fin credit app.
	 *
	 * @param companyId the company ID of this fin credit app
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this fin credit app.
	 *
	 * @return the user ID of this fin credit app
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this fin credit app.
	 *
	 * @param userId the user ID of this fin credit app
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this fin credit app.
	 *
	 * @return the user uuid of this fin credit app
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this fin credit app.
	 *
	 * @param userUuid the user uuid of this fin credit app
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this fin credit app.
	 *
	 * @return the user name of this fin credit app
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this fin credit app.
	 *
	 * @param userName the user name of this fin credit app
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this fin credit app.
	 *
	 * @return the create date of this fin credit app
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this fin credit app.
	 *
	 * @param createDate the create date of this fin credit app
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this fin credit app.
	 *
	 * @return the modified date of this fin credit app
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this fin credit app.
	 *
	 * @param modifiedDate the modified date of this fin credit app
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the account ID of this fin credit app.
	 *
	 * @return the account ID of this fin credit app
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this fin credit app.
	 *
	 * @param accountId the account ID of this fin credit app
	 */
	public void setAccountId(long accountId);

	/**
	 * Returns the applicant name of this fin credit app.
	 *
	 * @return the applicant name of this fin credit app
	 */
	@AutoEscape
	public String getApplicantName();

	/**
	 * Sets the applicant name of this fin credit app.
	 *
	 * @param applicantName the applicant name of this fin credit app
	 */
	public void setApplicantName(String applicantName);

	/**
	 * Returns the requested amount of this fin credit app.
	 *
	 * @return the requested amount of this fin credit app
	 */
	public double getRequestedAmount();

	/**
	 * Sets the requested amount of this fin credit app.
	 *
	 * @param requestedAmount the requested amount of this fin credit app
	 */
	public void setRequestedAmount(double requestedAmount);

	/**
	 * Returns the purpose of this fin credit app.
	 *
	 * @return the purpose of this fin credit app
	 */
	@AutoEscape
	public String getPurpose();

	/**
	 * Sets the purpose of this fin credit app.
	 *
	 * @param purpose the purpose of this fin credit app
	 */
	public void setPurpose(String purpose);

	/**
	 * Returns the status of this fin credit app.
	 *
	 * @return the status of this fin credit app
	 */
	public int getStatus();

	/**
	 * Sets the status of this fin credit app.
	 *
	 * @param status the status of this fin credit app
	 */
	public void setStatus(int status);

	/**
	 * Returns the review notes of this fin credit app.
	 *
	 * @return the review notes of this fin credit app
	 */
	@AutoEscape
	public String getReviewNotes();

	/**
	 * Sets the review notes of this fin credit app.
	 *
	 * @param reviewNotes the review notes of this fin credit app
	 */
	public void setReviewNotes(String reviewNotes);

	@Override
	public FinCreditApp cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}