/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package fin.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FinTransaction service. Represents a row in the &quot;FinServices_FinTransaction&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>fin.services.model.impl.FinTransactionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>fin.services.model.impl.FinTransactionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FinTransaction
 * @generated
 */
@ProviderType
public interface FinTransactionModel
	extends BaseModel<FinTransaction>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fin transaction model instance should use the {@link FinTransaction} interface instead.
	 */

	/**
	 * Returns the primary key of this fin transaction.
	 *
	 * @return the primary key of this fin transaction
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fin transaction.
	 *
	 * @param primaryKey the primary key of this fin transaction
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this fin transaction.
	 *
	 * @return the uuid of this fin transaction
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this fin transaction.
	 *
	 * @param uuid the uuid of this fin transaction
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the transaction ID of this fin transaction.
	 *
	 * @return the transaction ID of this fin transaction
	 */
	public long getTransactionId();

	/**
	 * Sets the transaction ID of this fin transaction.
	 *
	 * @param transactionId the transaction ID of this fin transaction
	 */
	public void setTransactionId(long transactionId);

	/**
	 * Returns the group ID of this fin transaction.
	 *
	 * @return the group ID of this fin transaction
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this fin transaction.
	 *
	 * @param groupId the group ID of this fin transaction
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this fin transaction.
	 *
	 * @return the company ID of this fin transaction
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this fin transaction.
	 *
	 * @param companyId the company ID of this fin transaction
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this fin transaction.
	 *
	 * @return the user ID of this fin transaction
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this fin transaction.
	 *
	 * @param userId the user ID of this fin transaction
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this fin transaction.
	 *
	 * @return the user uuid of this fin transaction
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this fin transaction.
	 *
	 * @param userUuid the user uuid of this fin transaction
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this fin transaction.
	 *
	 * @return the user name of this fin transaction
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this fin transaction.
	 *
	 * @param userName the user name of this fin transaction
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this fin transaction.
	 *
	 * @return the create date of this fin transaction
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this fin transaction.
	 *
	 * @param createDate the create date of this fin transaction
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this fin transaction.
	 *
	 * @return the modified date of this fin transaction
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this fin transaction.
	 *
	 * @param modifiedDate the modified date of this fin transaction
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the account ID of this fin transaction.
	 *
	 * @return the account ID of this fin transaction
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this fin transaction.
	 *
	 * @param accountId the account ID of this fin transaction
	 */
	public void setAccountId(long accountId);

	/**
	 * Returns the transaction type of this fin transaction.
	 *
	 * @return the transaction type of this fin transaction
	 */
	@AutoEscape
	public String getTransactionType();

	/**
	 * Sets the transaction type of this fin transaction.
	 *
	 * @param transactionType the transaction type of this fin transaction
	 */
	public void setTransactionType(String transactionType);

	/**
	 * Returns the amount of this fin transaction.
	 *
	 * @return the amount of this fin transaction
	 */
	public double getAmount();

	/**
	 * Sets the amount of this fin transaction.
	 *
	 * @param amount the amount of this fin transaction
	 */
	public void setAmount(double amount);

	/**
	 * Returns the description of this fin transaction.
	 *
	 * @return the description of this fin transaction
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this fin transaction.
	 *
	 * @param description the description of this fin transaction
	 */
	public void setDescription(String description);

	/**
	 * Returns the transaction date of this fin transaction.
	 *
	 * @return the transaction date of this fin transaction
	 */
	public Date getTransactionDate();

	/**
	 * Sets the transaction date of this fin transaction.
	 *
	 * @param transactionDate the transaction date of this fin transaction
	 */
	public void setTransactionDate(Date transactionDate);

	/**
	 * Returns the status of this fin transaction.
	 *
	 * @return the status of this fin transaction
	 */
	public int getStatus();

	/**
	 * Sets the status of this fin transaction.
	 *
	 * @param status the status of this fin transaction
	 */
	public void setStatus(int status);

	@Override
	public FinTransaction cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}